---
- name: install apt-get https transport and CA certificates
  apt:
    name: "{{item}}"
    state: latest
    update_cache: true
  with_items:
    - apt-transport-https
    - ca-certificates

- name: install easy_install
  apt: 
    name: python-setuptools
    state: latest

- name: install pip
  easy_install:
    name: pip
    state: latest

- name: install latest version of docker-py
  pip:
    name: docker-py
    state: latest

- name: add Docker's GPG key
  apt_key:
    id: 58118E89F3A912897C070ADBF76221572C52609D
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    state: present

- name: add Docker's APT repository
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo debian-jessie main
    update_cache: yes
    state: present

- name: install Docker Engine
  apt:
    name: docker-engine
    state: latest

- name: enable Docker service
  service:
    name: docker
    enabled: true

- name: add users to docker group
  user:
    name: "{{item}}"
    groups: docker
    state: present
  with_items: docker_users

- name: install docker-py
  apt:
    name: python-docker
    state: latest

- name: run hello-world container
  docker:
    name: helloworld
    image: hello-world
    state: started
  when: docker_run_helloworld == true
